name: Report an issue with Luciferin
about: Report an issue with Luciferin.
title: ""
issue_body: true
inputs:
  - type: textarea
    attributes:
      label: The problem
      required: true
      description: >-
        Describe the issue you are experiencing here. Please describe what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
