name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v2
    - name: Creating artifact
      uses: actions/upload-artifact@v1
      with:
        name: FastScreenCapture.jar
        path: target/FastScreenCapture-1.0-SNAPSHOT-jar-with-dependencies.jar