name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14.x.x'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup Jar filename to be used as artifact
      run: cp target/*jar-with-dependencies.jar target/FireflyLuciferin.jar

    - name: Creating artifact
      uses: actions/upload-artifact@v1
      with:
        name: FireflyLuciferin.jar
        path: target/FireflyLuciferin.jar