name: Create Release Linux

on: [push, pull_request]

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}

    name: Create Release
    runs-on: fedora-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14.x.x'

      - name: Get commit message
        run: |
           echo Commit MSG = $commitmsg

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2

